[project]
name = "rpn_calculator"
version = "1.0.0"
description = "RPN caluclator for UNI"
requires-python = ">=3.12"
authors = [
    {
        name = "Navruz",
        email = "nkkudratov@mai.education"
    }
]
dependencies = [
    "pytest>=8.4.2",
]
